### ISSUE TITLE
Ask for advice

### ISSUE THREAD

**Issue by zengjianyou** [M3DV/RibFrac-Challenge#2]
I have used many models to train this data, but the effect is very poor and there is no detection effect. Can anyone guide me?

**Comment by duducheng** [comment]
Thanks for your interests!

Actually it is not appropriate for the organizers to provide very detailed suggestions, but I could provide some information based on our own attemption on this data:
1. Our method based on segmentation methodology at least achieves a sensitivity of around 0.9, where ROI IoU>0.2 is regarded as a hit.
2. You should not use high IoU to regard detection "hit", since the target shape is generally elongated. Elongated shape is generally associated with low segmentation metrics compared to rounded shape. We indeed use IoU>0.2 to regard a detection hit for the challenge.
3. This task is a tricy task indeed, for both human and machine. Human experts could underperform this task than a well tuned deep model in terms of sensitivity, but outperform the model in terms of false positives (reduced FPs). We have conducted observer studies with 2 radiologists. 

We are submiting our paper these days; You may find the detailed methods and results after the paper is accepted. However, it is supposed to be after the challenge ddl.

Good luck! I hope these information could help.

**Comment by zengjianyou** [comment]
Sometimes I thought it was a data problem, because I did standardization and then 3D segmentation, which is okay. It is probably my model problem.thank you apply

**Comment by yyareyoung** [comment]
> Sometimes I thought it was a data problem, because I did standardization and then 3D segmentation, which is okay. It is probably my model problem.thank you apply

Hi, friend.  I tried to do with the 3D-Unet, but it didn't work. I think this is because the target is too small and the model only can detect the background information.  The train data has been standardized and cropped. Have you tried any other models? Thanks.

**Comment by zengjianyou** [comment]
@yyareyoung 
I also used unet-3D and it didn’t work. I thought it was a data problem. I also did some tailoring. I also suspected the data imbalance problem. So I’m solving it. We can discuss it together. My wechat: 13576132131
